### ISSUE TITLE
Is there anybody who will use a Port to Python 3 of this activity?  We think not.  Speak up.

### ISSUE THREAD

**Issue by srevinsaju** [163gal/Java#2]

**Comment by quozl** [comment]
Thanks, but I doubt a port is needed.  The activity was created for the OLPC XO so that Java programs could be run.  At the time Java could not be distributed by OLPC because of licensing uncertainties, so other people made an "activity" that could be installed by a teacher or child.

While the OLPC XO is still on Fedora 18 with Python 2, there's no use-case for a Python 3 port.

Later laptops that run Sugar can install the Java packages from the distribution (e.g. Ubuntu), or use Flatpaks.

If someone needs this ported would they please speak up to counter my opinion?

**Comment by srevinsaju** [comment]
I guess the title should be changed then, it might misguide future contributors. Thanks for this info.

**Comment by srevinsaju** [comment]
Nice :)
